[structs.VxDDescBlock]
members = [
    { type = "u32", name = "DDB_Next" },
    { type = "u16", name = "DDB_SDK_Version" },
    { type = "u16", name = "DDB_Req_Device_Number" },
    { type = "u8", name = "DDB_Dev_Major_Version" },
    { type = "u8", name = "DDB_Dev_Minor_Version" },
    { type = "u16", name = "DDB_Flags" },
    { type = "char", name = "DDB_Name", count = 8 },
    { type = "u32", name = "DDB_Init_Order" },
    { type = "u32", name = "DDB_Control_Proc" },
    { type = "u32", name = "DDB_V86_API_Proc" },
    { type = "u32", name = "DDB_PM_API_Proc" },
    { type = "u32", name = "DDB_V86_API_CSIP" },
    { type = "u32", name = "DDB_PM_API_CSIP" },
    { type = "u32", name = "DDB_Reference_Data" },
    { type = "u32", name = "DDB_Service_Table_Ptr" },
    { type = "u32", name = "DDB_Service_Table_Size" },
    { type = "u32", name = "DDB_Win32_Service_Table" },
    { type = "u32", name = "DDB_Prev" },
    { type = "u32", name = "DDB_Size" },
    { type = "u32", name = "DDB_Reserved1" },
    { type = "u32", name = "DDB_Reserved2" },
    { type = "u32", name = "DDB_Reserved3" },
]
