[structs.PE_EXPORT_DIRECTORY]
members = [
    { type = "u32", name = "Characteristics" },
    { type = "u32", name = "TimeDateStamp" },
    { type = "u16", name = "MajorVersion" },
    { type = "u16", name = "MinorVersion" },
    { type = "u32", name = "Name" },
    { type = "u32", name = "Base" },
    { type = "u32", name = "NumberOfFunctions" },
    { type = "u32", name = "NumberOfNames" },
    { type = "u32", name = "AddressOfFunctions" },
    { type = "u32", name = "AddressOfNames" },
    { type = "u32", name = "AddressOfNameOrdinals" },
]

[structs.PE_IMPORT_DESCRIPTOR]
members = [
    { type = "u32", name = "OriginalFirstThunk" },
    { type = "u32", name = "TimeDateStamp" },
    { type = "u32", name = "ForwarderChain" },
    { type = "u32", name = "Name" },
    { type = "u32", name = "FirstThunk" },
]

[structs.PE_RESOURCE_DIRECTORY]
members = [
    { type = "u32", name = "Characteristics" },
    { type = "u32", name = "TimeDateStamp" },
    { type = "u16", name = "MajorVersion" },
    { type = "u16", name = "MinorVersion" },
    { type = "u16", name = "NumberOfNamedEntries" },
    { type = "u16", name = "NumberOfIdEntries" },
]

[structs.PE_RESOURCE_DIRECTORY_ENTRY]
members = [
    { type = "u32", name = "NameOffset" },
    { type = "u32", name = "OffsetToData" },
]

[structs.PE_RESOURCE_DATA_ENTRY]
members = [
    { type = "u32", name = "OffsetToData" },
    { type = "u32", name = "Size" },
    { type = "u32", name = "CodePage" },
    { type = "u32", name = "Reserved" },
]

[structs.PE_RUNTIME_FUNCTION_ENTRY]
members = [
    { type = "u32", name = "BeginAddress" },
    { type = "u32", name = "EndAddress" },
    { type = "u32", name = "UnwindInfoAddress" },
]

[structs.PE_DEBUG_DIRECTORY]
members = [
    { type = "u32", name = "Characteristics" },
    { type = "u32", name = "TimeDateStamp" },
    { type = "u16", name = "MajorVersion" },
    { type = "u16", name = "MinorVersion" },
    { type = "u32", name = "Type" },
    { type = "u32", name = "SizeOfData" },
    { type = "u32", name = "AddressOfRawData" },
    { type = "u32", name = "PointerToRawData" },
]

[structs.PE_TLS_DIRECTORY32]
members = [
    { type = "u32", name = "StartAddressOfRawData" },
    { type = "u32", name = "EndAddressOfRawData" },
    { type = "u32", name = "AddressOfIndex" },
    { type = "u32", name = "AddressOfCallBacks" },
    { type = "u32", name = "SizeOfZeroFill" },
    { type = "u32", name = "Characteristics" },
]

[structs.PE_TLS_DIRECTORY64]
members = [
    { type = "u64", name = "StartAddressOfRawData" },
    { type = "u64", name = "EndAddressOfRawData" },
    { type = "u64", name = "AddressOfIndex" },
    { type = "u64", name = "AddressOfCallBacks" },
    { type = "u32", name = "SizeOfZeroFill" },
    { type = "u32", name = "Characteristics" },
]

[structs.PE_LOAD_CONFIG_DIRECTORY32]
members = [
    { type = "u32", name = "Size" },
    { type = "u32", name = "TimeDateStamp" },
    { type = "u16", name = "MajorVersion" },
    { type = "u16", name = "MinorVersion" },
    { type = "u32", name = "GlobalFlagsClear" },
    { type = "u32", name = "GlobalFlagsSet" },
    { type = "u32", name = "CriticalSectionDefaultTimeout" },
    { type = "u32", name = "DeCommitFreeBlockThreshold" },
    { type = "u32", name = "DeCommitTotalFreeThreshold" },
    { type = "u32", name = "LockPrefixTable" },
    { type = "u32", name = "MaximumAllocationSize" },
    { type = "u32", name = "VirtualMemoryThreshold" },
    { type = "u32", name = "ProcessHeapFlags" },
    { type = "u32", name = "ProcessAffinityMask" },
    { type = "u16", name = "CSDVersion" },
    { type = "u16", name = "Reserved1" },
    { type = "u32", name = "EditList" },
    { type = "u32", name = "SecurityCookie" },
    { type = "u32", name = "SEHandlerTable" },
    { type = "u32", name = "SEHandlerCount" },
    { type = "u32", name = "GuardCFCheckFunctionPointer" },
    { type = "u32", name = "Reserved2" },
    { type = "u32", name = "GuardCFFunctionTable" },
    { type = "u32", name = "GuardCFFunctionCount" },
    { type = "u32", name = "GuardFlags" },
]

[structs.PE_LOAD_CONFIG_DIRECTORY64]
members = [
    { type = "u32", name = "Size"},
    { type = "u32", name = "TimeDateStamp"},
    { type = "u16", name = "MajorVersion"},
    { type = "u16", name = "MinorVersion"},
    { type = "u32", name = "GlobalFlagsClear"},
    { type = "u32", name = "GlobalFlagsSet"},
    { type = "u32", name = "CriticalSectionDefaultTimeout"},
    { type = "u64", name = "DeCommitFreeBlockThreshold"},
    { type = "u64", name = "DeCommitTotalFreeThreshold"},
    { type = "u64", name = "LockPrefixTable"},
    { type = "u64", name = "MaximumAllocationSize"},
    { type = "u64", name = "VirtualMemoryThreshold"},
    { type = "u64", name = "ProcessAffinityMask"},
    { type = "u64", name = "ProcessHeapFlags"},
    { type = "u16", name = "CSDVersion"},
    { type = "u16", name = "Reserved1"},
    { type = "u64", name = "EditList"},
    { type = "u64", name = "SecurityCookie"},
    { type = "u64", name = "SEHandlerTable"},
    { type = "u64", name = "SEHandlerCount"},
    { type = "u64", name = "GuardCFCheckFunctionPointer"},
    { type = "u64", name = "Reserved2"},
    { type = "u64", name = "GuardCFFunctionTable"},
    { type = "u64", name = "GuardCFFunctionCount"},
    { type = "u32", name = "GuardFlags"},
]

[structs.CV_INFO_PDB20]
members = [
    { type = "u32", name = "CvSignature" },
    { type = "u32", name = "Offset" },
    { type = "u32", name = "Signature" },
    { type = "u32", name = "Age" },
]

[structs.CV_INFO_PDB70]
members = [
    { type = "u32", name = "CvSignature" },
    { type = "u8",  name = "Signature", count = 16 },
    { type = "u32", name = "Age" },
]

[structs.PE_EH_FUNCINFO_CANDIDATE]
members = [
    { type = "u32", name = "magicAndBbtFlags" },
]
