[bios.sel]
a0 = "bios.A"
b0 = "bios.B"
c0 = "bios.C"

[bios.A]
00 = "open"
01 = "lseek"
02 = "read"
03 = "write"
04 = "close"
05 = "ioctl"
06 = "exit"
07 = "isatty"
08 = "getc"
09 = "putc"
0a = "todigit"
0b = "atof"
0c = "strtoul"
0d = "strtol"
0e = "abs"
0f = "labs"
10 = "atoi"
11 = "atol"
12 = "atob"
13 = "setjmp"
14 = "longjmp"
15 = "strcat"
16 = "strncat"
17 = "strcmp"
18 = "strncmp"
19 = "strcpy"
1a = "strncpy"
1b = "strlen"
1c = "index"
1d = "rindex"
1e = "strchr"
1f = "strrchr"
20 = "strpbrk"
21 = "strspn"
22 = "strcspn"
23 = "strtok"
24 = "strstr"
25 = "toupper"
26 = "tolower"
27 = "bcopy"
28 = "bzero"
29 = "bcmp"
2a = "memcpy"
2b = "memset"
2c = "memmove"
2d = "memcmp"
2e = "memchr"
2f = "rand"
30 = "srand"
31 = "qsort"
32 = "strtod"
33 = "malloc"
34 = "free"
35 = "lsearch"
36 = "bsearch"
37 = "calloc"
38 = "realloc"
39 = "InitHeap"
3a = "_exit"
3b = "getchar"
3c = "putchar"
3d = "gets"
3e = "puts"
3f = "printf"
40 = "SystemErrorUnresolvedException"
41 = "LoadTest"
42 = "Load"
43 = "Exec"
44 = "FlushCache"
45 = "init_a0_b0_c0_vectors"
46 = "GPU_dw"
47 = "gpu_send_dma"
48 = "SendGP1Command"
49 = "GPU_cw"
4a = "GPU_cwp"
4b = "send_gpu_linked_list"
4c = "gpu_abort_dma"
4d = "GetGPUStatus"
4e = "gpu_sync"
51 = "LoadExec"
54 = "_96_init"
55 = "_bu_init"
56 = "_96_remove"
5b = "dev_tty_init"
5c = "dev_tty_open"
5e = "dev_tty_ioctl"
5f = "dev_cd_open"
60 = "dev_cd_read"
61 = "dev_cd_close"
63 = "dev_cd_firstfile"
64 = "dev_cd_nextfile"
65 = "dev_cd_chdir"
66 = "dev_card_open"
67 = "dev_card_read"
68 = "dev_card_write"
69 = "dev_card_close"
6a = "dev_card_firstfile"
6b = "dev_card_nextfile"
6c = "dev_card_erase"
6d = "dev_card_undelete"
6e = "dev_card_format"
6f = "dev_card_rename"
71 = "_96_init"
72 = "_96_remove"
78 = "CdAsyncSeekL"
7c = "CdAsyncGetStatus"
7e = "CdAsyncReadSector"
81 = "CdAsyncSetMode"
90 = "CdromIoIrqFunc1"
91 = "CdromDmaIrqFunc1"
92 = "CdromIoIrqFunc2"
93 = "CdromDmaIrqFunc2"
94 = "CdromGetInt5errCode"
95 = "CdInitSubFunc"
96 = "AddCDROMDevice"
97 = "AddMemCardDevice"
98 = "AddDuartTtyDevice"
99 = "AddDummyTtyDevice"
9c = "SetConf"
9d = "GetConf"
9e = "SetCdromIrqAutoAbort"
9f = "SetMem"
a0 = "_boot"
a1 = "SystemError"
a2 = "EnqueueCdIntr"
a3 = "DequeueCdIntr"
a4 = "CdGetLbn"
a5 = "CdReadSector"
a6 = "CdGetStatus"
a7 = "bufs_cb_0"
a8 = "bufs_cb_1"
a9 = "bufs_cb_2"
aa = "bufs_cb_3"
ab = "_card_info"
ac = "_card_load"
ad = "_card_auto"
ae = "bufs_cb_4"
af = "card_write_test"
b2 = "_ioabort_raw"
b4 = "GetSystemInfo"

[bios.B]
00 = "alloc_kernel_memory"
01 = "free_kernel_memory"
02 = "init_timer"
03 = "get_timer"
04 = "enable_timer_irq"
05 = "disable_timer_irq"
06 = "restart_timer"
07 = "DeliverEvent"
08 = "OpenEvent"
09 = "CloseEvent"
0a = "WaitEvent"
0b = "TestEvent"
0c = "EnableEvent"
0d = "DisableEvent"
0e = "OpenTh"
0f = "CloseTh"
10 = "ChangeTh"
12 = "InitPAD2"
13 = "StartPAD2"
14 = "StopPAD2"
15 = "PAD_init2"
16 = "PAD_dr"
17 = "ReturnFromException"
18 = "ResetEntryInt"
19 = "HookEntryInt"
20 = "UnDeliverEvent"
32 = "open"
33 = "lseek"
34 = "read"
35 = "write"
36 = "close"
37 = "ioctl"
38 = "exit"
39 = "isatty"
3a = "getc"
3b = "putc"
3c = "getchar"
3d = "putchar"
3e = "gets"
3f = "puts"
40 = "cd"
41 = "format"
42 = "firstfile2"
43 = "nextfile"
44 = "rename"
45 = "erase"
46 = "undelete"
47 = "AddDrv"
48 = "RemoveDrv"
4a = "InitCARD2"
4b = "StartCARD2"
4c = "StopCARD2"
4d = "_card_info_subfunc"
4e = "_card_write"
4f = "_card_read"
50 = "_new_card"
54 = "_get_errno"
55 = "_get_error"
56 = "GetC0Table"
57 = "GetB0Table"
58 = "_card_chan"
59 = "testdevice"
5c = "_card_status"
5d = "_card_wait"

[bios.C]
00 = "EnqueueTimerAndVblankIrqs"
01 = "EnqueueSyscallHandler"
02 = "SysEnqIntRP"
03 = "SysDeqIntRP"
04 = "get_free_EvCB_slot"
05 = "get_free_TCB_slot"
06 = "ExceptionHandler"
07 = "InstallExceptionHandlers"
08 = "SysInitMemory"
09 = "SysInitKernelVar"
0a = "ChangeClearRCnt"
0c = "InitDefInt"
0d = "SetIrqAutoAck"
19 = "_ioabort"
1a = "set_card_find_mode"
1c = "SysMalloc"
1d = "get_card_find_mode"
