[manifest]
callconv = "stdcall"

[prototypes.DLGPROC]
ret = {type = "usize"}
args = [
    { type = "usize", name = "hDlg" },
    { type = "u32", name = "uMsg" },
    { type = "usize", name = "wParam" },
    { type = "usize", name = "lParam" },
]

[functions.DialogBoxParamA]
ret = {type = "usize"}
args = [
    { type = "usize", name = "hInstance" },
    { type = "char", name = "lpTemplateName", mod = "ptr" },
    { type = "usize", name = "hWndParent" },
    { type = "DLGPROC", name = "lpDialogFunc" },
    { type = "usize", name = "lParam" },
]

[functions.EndDialog]
ret = { type = "bool" }
args = [
    { type = "usize", name = "hDlg" },
    { type = "usize", name = "nResult" },
]
