[manifest]
callconv = "stdcall"

[functions.DialogBoxParamA]
ret = {type = "usize"}
args = [
    { type = "usize", name = "hInstance" },
    { type = "char", name = "lpTemplateName", mod = "ptr" },
    { type = "usize", name = "hWndParent" },
    { type = "function", name = "lgDialogFunc" }, # TODO: DLGPROC
    { type = "usize", name = "lParam" },
]

[functions.EndDialog]
ret = { type = "bool" }
args = [
    { type = "usize", name = "hDlg" },
    { type = "usize", name = "nResult" },
]
