[structs.RTTI_CompleteObjectLocator32]
members = [
    { type = "u32", name = "signature" },
    { type = "u32", name = "offset" },
    { type = "u32", name = "cdOffset" },
    { type = "u32", name = "pTypeDescriptor" },
    { type = "u32", name = "pClassDescriptor" },
]

[structs.RTTI_CompleteObjectLocator64]
members = [
    { type = "u32", name = "signature" },
    { type = "u32", name = "offset" },
    { type = "u32", name = "cdOffset" },
    { type = "u32", name = "pTypeDescriptor" },
    { type = "u32", name = "pClassDescriptor" },
    { type = "u32", name = "pSelf" },
]

[structs.RTTI_ClassHierarchyDescriptor]
members = [
    { type = "u32", name = "signature" },
    { type = "u32", name = "attributes" },
    { type = "u32", name = "numBaseClasses" },
    { type = "u32", name = "pBaseClassArray" },
]

[structs.RTTI_BaseClassDescriptor]
members = [
    { type = "u32", name = "pTypeDescriptor"},
    { type = "u32", name = "numContainedBases" },
    { type = "i32", name = "where_mdisp" },
    { type = "i32", name = "where_pdisp" },
    { type = "i32", name = "where_vdisp" },
    { type = "u32", name = "attributes" },
    { type = "u32", name = "pClassDescriptor" },
]

[structs.RTTI_TypeDescriptor]
members = [
    { type = "usize", name = "pVFTable", mod = "ptr" },
    { type = "usize", name = "spare", mod = "ptr" },
]
